name: git-buildpackage native packaging

on:
  workflow_call:
    secrets:
      GPG_PRIVATE_KEY:
        required: true
    inputs:
      DEBFULLNAME:
        required: true
        type: string
      DEBEMAIL:
        required: true
        type: string
      before_build_deps_install:
        type: string

env:
  DEBFULLNAME: ${{ inputs.DEBFULLNAME }}
  DEBEMAIL: ${{ inputs.DEBEMAIL }}

jobs:

  build-native:
    name: ${{ matrix.distro }} native
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - container: "ubuntu:latest"
            distro: "ubuntu_latest"
          - container: "debian:latest"
            distro: "debian_latest"

    container:
      image: ${{ matrix.container }}
      env:
        DEBIAN_FRONTEND: noninteractive

    steps:
      # because job is in container
      - name: latest git from backports
        # https://github.com/actions/runner/issues/1533
        shell: bash
        run: |
          # https://github.com/actions/runner-images/issues/675
          echo 'Acquire::Retries "3";' | tee /etc/apt/apt.conf.d/99ci

          # install lsb-release and git
          apt-get update
          apt-get install -y lsb-release git
      - name: check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: source
      - name: install
        # https://github.com/actions/runner/issues/1533
        shell: bash
        run: |
          git config --global user.name "${DEBFULLNAME}"
          git config --global user.email "${DEBEMAIL}"

          apt-get install -y debhelper-compat git-buildpackage equivs
      - name: build deb
        # https://github.com/actions/runner/issues/1533
        shell: bash
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import

          DISTCODENAME=$(lsb_release -c -s)

          ${{ inputs.before_build_deps_install }}

          # install build depends and remove resulting clutter
          mk-build-deps -i -r source/debian/control -t "apt-get -y -o Debug::pkgProblemResolver=yes --no-install-recommends --yes"
          rm -f *.deb *.buildinfo *.changes

          pushd source

          PARENTVERSION=$(dpkg-parsechangelog --show-field Version)
          dch -b -D "${DISTCODENAME}" -v "${PARENTVERSION}~${DISTCODENAME}" "Release for ${DISTCODENAME}"
          git add .
          git commit -m "Update changelog for $(dpkg-parsechangelog --show-field Version) release"

          gbp buildpackage -F --git-export-dir=.. --git-ignore-branch

          popd
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.distro }}-native
          retention-days: 1
          path: |
            *.buildinfo
            *.changes
            *.ddeb
            *.deb
            *.dsc
            *.tar*
